all:
	gcc hide_test.c -o hide_test
	gcc masq_test.c -o masq_test
	gcc filter_test_source.c -o filter_test
	gcc filter_test.c -o read_filter_1
	gcc filter_test.c -o read_filter_2
	gcc filter_test.c -o read_filter_3
	gcc filter_test.c -o write_filter_1
	gcc filter_test.c -o write_filter_2
	gcc filter_test.c -o write_filter_3
	gcc filter_test.c -o rw_filter_1
	gcc filter_test.c -o rw_filter_2
clean:
	rm -rf hide_test masq_test filter_test read_filter_1 read_filter_2 read_filter_3 
	rm -rf write_filter_1 write_filter_2 write_filter_3 rw_filter_1 rw_filter_2

